/**
 * Topics actions
 */
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

/**
 * Cloud actions
 */
export const RELOAD_TOPICS_REQUEST = 'RELOAD_TOPICS_REQUEST';
export const CLOUD_PROCESS_START = 'CLOUD_PROCESS_START';
export const CLOUD_PROCESS_END = 'CLOUD_PROCESS_END';
export const UPDATE_SELECTED_WORD_ID = 'UPDATE_SELECTED_WORD_ID';
export const UPDATE_INFO_BAR_PIE_CHART_PERCENTAGE = 'UPDATE_INFO_BAR_PIE_CHART_PERCENTAGE';

/**
 * Cloud actions
 */
export const MODIFY_INFO_PANEL_DISPLAY = 'MODIFY_INFO_PANEL_DISPLAY';
